"use client";

import { useState } from "react";
import { useToast } from "@/hooks/use-toast";
import { Header } from "@/components/layout/header";
import { RoomForm } from "@/components/room-form";
import { RecommendationDisplay } from "@/components/recommendations/recommendation-display";
import { getRoomRecommendations } from "@/app/actions";
import { Separator } from "@/components/ui/separator";
import type { RoomAizeResult, EnrichedItemRecommendation } from "@/lib/types";

type ResultState = RoomAizeResult | { error: string };

export default function Home() {
  const [recommendations, setRecommendations] = useState<RoomAizeResult | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const { toast } = useToast();

  const handleFormSubmit = async (formData: unknown) => {
    setIsLoading(true);
    setRecommendations(null);

    const result: ResultState = await getRoomRecommendations(formData);

    if ("error" in result && result.error) {
      toast({
        variant: "destructive",
        title: "An error occurred",
        description: result.error,
      });
    } else if ("colors" in result) {
      setRecommendations(result);
    }
    setIsLoading(false);
  };

  return (
    <div className="min-h-screen bg-background text-foreground">
      <Header />
      <main className="container mx-auto px-4 py-8">
        <div className="grid lg:grid-cols-12 gap-12">
          <div className="lg:col-span-4 xl:col-span-3">
            <RoomForm onSubmit={handleFormSubmit} isLoading={isLoading} />
          </div>
          <div className="lg:col-span-8 xl:col-span-9">
            <RecommendationDisplay
              recommendations={recommendations}
              isLoading={isLoading}
            />
          </div>
        </div>
        <Separator className="my-12" />
        <div className="text-center text-muted-foreground text-xs max-w-2xl mx-auto">
          <p className="font-semibold mb-1">AI Disclaimer</p>
          <p>
            RoomAIze uses generative AI. The suggestions for colors, furniture,
            and decor are generated by an AI model and may contain unexpected or
            inaccurate information. Please verify all details before making any
            purchasing decisions.
          </p>
        </div>
      </main>
    </div>
  );
}
